### ISSUE TITLE
"popen//python=python2.7" keeps failing on windows

### ISSUE THREAD

**Issue by iftahro** [pytest-dev/execnet#125]
Please add `shell=True` into `self.subprocess.Popen(args, stdout=PIPE, stdin=PIPE)` in module `gatewy_base.ExecModel.PopenPiped`, because currently `execnet.makegateway("popen//python=python2.7")` only works with Unix-ish systems.

Changes to be made:
![image](https://user-images.githubusercontent.com/57870811/116589909-d3f70f00-a925-11eb-9bf6-2285ee5abcdb.png)

The exception right now:
![image](https://user-images.githubusercontent.com/57870811/116591114-284ebe80-a927-11eb-9bab-6cb4cf5967d5.png)

**Comment by nicoddemus** [comment]
Hi @iftahro,

This library is not really getting much maintenance, but would accept a PR in that direction (including a failing test). 👍

**Comment by RonnyPfannschmidt** [comment]
closing as not planned, shell=true is tricky

im open to a contrbution of a popen_shell xspec
