### ISSUE TITLE
UnicodeEncodeError when source-path includes a special character

### ISSUE THREAD

**Issue by ewuerger** [pytest-dev/execnet#153]
Hi,

while I configured pytest via the pytest.ini in VS Code for running tests in parallel as suggested [here](https://code.visualstudio.com/docs/python/testing#_run-tests-in-parallel) I encountered a UnicodeEncodeError. I've chosen the name of my work path as `wörk` out of humour. But it's exactly the 'ö' aka. '\xf6' which is a problem for `sendexec` in gateway_bootstrap.py.

```python
def sendexec(io, *sources):
    source = "\n".join(sources)
    io.write((repr(source) + "\n").encode("utf-8"))
```
fixes it. I don't understand why one ever uses ascii encoding when dealing with filepaths. Could you explain?

**Comment by RonnyPfannschmidt** [comment]
please include more details, its absolutely unclear what's happening, what the trace-back is and how to reproduce

**Comment by ewuerger** [comment]
Ok. Let me be more precise:
This is the pytest.ini:
```
 [pytest]
 addopts=-n4
```
and then I just run pytest with it or use the test identification of vs code and run them via the gui. Then it breaks in https://github.com/pytest-dev/execnet/blob/5d7f5024137bdaa87ff73032ca9f54b1c111b9d6/execnet/gateway_bootstrap.py#L77-L79
on the last line with an `UnicodeEncodeError` because of the "ascii" encoding. Whenever the user has a special character in its path, like I do( 'ö' aka. '\xf6'), this will break. I think it is not optimal to have that... but I'm curious on why you don't use "utf-8" in the first place.

**Comment by RonnyPfannschmidt** [comment]
im working on replacing this with unicode-escape and/or compression
