### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by mgorny** [pytest-dev/execnet#162]
Could you make a new release, please? The tests in the current version no longer works with new pytest (c0459b92bc4a42b08281e69b8802d24c5d3415d4 is needed).

**Comment by nicoddemus** [comment]
Hi @mgorny,

AFAICT we don't have any new features/bug fixes warranting a new release. We usually do not make a new release to end-users for code changes that only affect the internal tests (which are not even shipped with the package).

Why do you need a new PyPI release?

**Comment by mgorny** [comment]
We're running tests as part of Gentoo packages, and the patch needed to make them work again is quite large.

**Comment by nicoddemus** [comment]
@mgorny but the tests are not part of the package... do you folks build from source, but from a release tag?

**Comment by mgorny** [comment]
Yes, we use GitHub archives from tags (when pypi sdists aren't sufficient).

**Comment by nicoddemus** [comment]
I see, thanks.

Any chance of applying c0459b9 as a patch then? I understand is quite large, but I don't see that as a problem given `execnet` is mostly in maintenance mode.

Just to clarify, making a new release does not take much time for us maintainers, that is not a problem, however I'm a bit reluctant to make a new release which will have zero updates for end-users (as basically that patch just touches tests, which are not packaged). A new release triggers all kind of updates downstream (dependabot just one of them), for thousands of users, so I would like to avoid doing that without very strong reason.

If we had any bug fix or user-facing changes I would probably have prepared the release already.

**Comment by mgorny** [comment]
Yeah, I suppose that's fine. I didn't think of dependabot.

**Comment by jaraco** [comment]
I was about to open a bug about the codebase being stale when I found this one. I'm running the latest release of execnet (1.9.0) but the tracebacks I get don't match what's displayed here.
