### ISSUE TITLE
Discovering the child pid of a popen gateway

### ISSUE THREAD

**Issue by kailizcatman** [pytest-dev/execnet#166]
In an application I am maintaining, I use execnet to launch and interact with a child process that can potentially open a few files on the disk. I use `Gateway.exit` to make sure that the child process has properly exited before trying to delete those files.

However, it seems that there is sometimes a delay between the `Gateway.exit` call and the child fully terminating. I would like to use `os.waitpid` to block the main process until the child process has actually exited. Using `os.waitpid` is also safer in an application with potentially other child processes.

What is the best way to find out the pid of the child process in a popen gateway? Two methods that I have considered:

- `Gateway._io.popen.processid` This seems to work, but I am not sure whether the `_io` variable will be there in future versions.
- Send a `import os;channel.send(os.getpid())` to the child proess.

**Comment by RonnyPfannschmidt** [comment]
The gateway group termination will wait for termination completion

If you use multiple gateways, that's the recommended api anyway

**Comment by kailizcatman** [comment]
If I do not explicitly create a gateway group, would the function to call `execnet.defaultgateway.terminate`?

Given a `Gateway` instance object, how best to find its gateway group?

**Comment by RonnyPfannschmidt** [comment]
currently the gatway exposes the group only via the `_group` attribute
