### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/execnet#199]
...do we have release plans though?  It's been two years, but https://github.com/pytest-dev/execnet/compare/v1.9.0...master is a lot of bugfixes to keep off PyPI.  I'm just going to install from the commit, but it'd be nice to share more widely.

_Originally posted by @Zac-HD in https://github.com/pytest-dev/execnet/issues/196#issuecomment-1620597483_

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt any blockers in your opinion, or can we go ahead and release 2.0?

**Comment by RonnyPfannschmidt** [comment]
I'll need to give it a look

**Comment by Zac-HD** [comment]
It'd be nice to include  https://github.com/pytest-dev/execnet/issues/153 as well, it's only ever used to send Python source code changing to `encoding="utf-8"` is correct and a very quick fix.

**Comment by RonnyPfannschmidt** [comment]
im ok with a 2.0 release asap

the work in #174 was supposed to make a implied fix for #153 - however that has not yet manifested and will likely need a few more work timframes dedicated to it

if anyone is up for a quickfiix for #153 im happy to review it, but i cant commit to making one within the net 2-3 months myself

**Comment by nicoddemus** [comment]
Fixed in #203.
