### ISSUE TITLE
Feature - Provide pickle as a solution to serialize non-builtin or supported types. 

### ISSUE THREAD

**Issue by sanchayanghosh** [pytest-dev/execnet#223]
As of today, the builtin serializers cannot work with objects/type variables that are not supported in execnet directly. However, as pointed before - pickle can be used to serialize and de-serialize unsupported objects.

To start with, we can put a conditional that if save_* function is not implemented, we will directly write to the socket using pickle. And then gradually if needed replace other built-in types.

**Comment by RonnyPfannschmidt** [comment]
eventually per channel serializers will be provided, expanding the serializer as is, is not planned
