### ISSUE TITLE
The error is not being catched

### ISSUE THREAD

**Issue by Rulisock27** [pytest-dev/execnet#233]
import speech_recognition as sr                     
from openai import OpenAI
from pathlib import Path 
from kivymd.app import MDApp
from kivy.uix.screenmanager import Screen, ScreenManager, FadeTransition
from kivy.uix.image import AsyncImage  # Corrected import
from kivymd.uix.label import MDLabel
from kivy.clock import Clock
import sounddevice as sd
import librosa
import numpy as np 

class TalkAI(Screen):
    def __init__(self, **kwa):
        super(TalkAI, self).__init__(**kwa)
        bgimg = AsyncImage(source="background.png", allow_stretch=True, keep_ratio=False, size_hint=(1, 1))
        self.add_widget(bgimg)

        self.loop = False  # Initialize loop variable

    def run_chatbot(self, dt):
        try:
            api_key = ""
            r = sr.Recognizer()
            mic = sr.Microphone(device_index=0)
            conversation = ""
            user_name = "Adi"
            bot_name = "Bliss Buddy"

            with mic as source:
                Listening = MDLabel(text="\nListening...", pos_hint={'x': 0.3, 'y': 0.39}, font_style="H5")
                self.add_widget(Listening)

                r.adjust_for_ambient_noise(source, duration=0.2)
                audio = r.listen(source)

            Response = MDLabel(text="Please wait...", pos_hint={'x': 0.5, 'y': 0.56}, font_style="H5")
            self.add_widget(Response)

            try:
                user_input = r.recognize_google(audio)
            except sr.UnknownValueError:
                return
            except sr.RequestError as e:
                print(f"Error in recognizing speech: {e}")
                Error = MDLabel(text=f"Could not request results from Google Speech Recognition service; {e}",
                                pos_hint={"x": 0.8, "y": 0.65}, font_style="H5")
                self.add_widget(Error)
                return

            User_Input = MDLabel(text=f"User said: {user_input}", pos_hint={"x": 0.4, "y": 0.34}, font_style="H5")
            self.add_widget(User_Input)

            # Check if the user wants to exit
            if "bye-bye bot" in user_input.lower():
                Bye_Bye = MDLabel(text="Goodbye!", pos_hint={'x': 0.6, "y": 0.45}, font_style="H5")
                self.add_widget(Bye_Bye)
                Clock.unschedule(self.run_chatbot)  # Unschedule the interval
                return

            # Process user input as a regular conversation with the chatbot
            prompt = user_name + ":" + user_input + "\n" + bot_name + ":"
            conversation += prompt

            client = OpenAI(api_key=api_key)
            response = client.completions.create(
                model="text-davinci-003",
                prompt=conversation,
                temperature=0.6,  # Adjust this value to control the randomness of the response
                max_tokens=256,
                top_p=1,
                frequency_penalty=0,
                presence_penalty=0
            )

            response_str = response.choices[0].text
            response_str = response_str.split(user_name + ":", 1)[0].split(bot_name + ":", 1)[0]

            conversation += response_str + "\n"

            User_Response = MDLabel(text=response_str, pos_hint={"x": 0.5, "y": 0.55}, font_style="H5")
            self.add_widget(User_Response)

            speech_file_path = Path(__file__).parent / "speech.wav"

            response = client.audio.speech.create(
                model="tts-1",
                voice="nova",
                input=response_str)

            response.stream_to_file(speech_file_path)
            audio_data, sample_rate = librosa.load(speech_file_path, sr=None)

            sd.play(audio_data, sample_rate)
            sd.wait()

        except Exception as e:
            print(f"An error occurred: {e}")
            import traceback
            traceback.print_exc()

            Clock.unschedule(self.run_chatbot)  # Unschedule the interval on error
            Error = MDLabel(text=f"An error occurred: {e}", pos_hint={"x": 0.8, "y": 0.65}, font_style="H5")
            self.add_widget(Error)
            self.loop = False  # Exit the loop on error

    def on_enter(self):
        self.loop = True
        Clock.schedule_interval(self.run_chatbot, 1.0)  # Adjust the interval as needed

    def on_leave(self):
        Clock.unschedule(self.run_chatbot)  # Unschedule the interval when leaving the screen

class MindMagic(MDApp):
    def build(self):
        self.theme_cls.material_style = "M3"
        self._app_name = "RakshaKavach"
        self.icon = "logo.png"
        sm = ScreenManager(transition=FadeTransition())
        sm.add_widget(TalkAI(name="talkai"))
        return sm

if __name__ == "__main__":
    MindMagic().run()

[INFO   ] [Logger      ] Record log in C:\Users\PIYUSH\.kivy\logs\kivy_23-12-05_39.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.6.0
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "C:\Users\PIYUSH\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\PIYUSH\AppData\Local\Programs\Python\Python39\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-11-19 (installed at "C:\Users\PIYUSH\AppData\Local\Programs\Python\Python39\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.5.1
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 31.0.101.4575'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 31.0.101.4575'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
Error in sys.excepthook:

Original exception was:

this is the error pls help me out

**Comment by RonnyPfannschmidt** [comment]
Nothing in this is related to execnet
