### ISSUE TITLE
Python freezes in gw.remote_exec()

### ISSUE THREAD

**Issue by muh182** [pytest-dev/execnet#72]
I am following up on [this issue](https://github.com/jythontools/jython/issues/99) that I have asked the jython development team.

**Comment by RonnyPfannschmidt** [comment]
i did a small investigation, based on https://github.com/pytest-dev/execnet/blob/3ea8374724f436a3a73ffc2e481dc2a66b208a97/execnet/gateway_bootstrap.py#L91-L102 the sys.path setup is correct

there exists a potential of this being a unintended threading issue happening on more modern jython which would take immense time to debug

**Comment by muh182** [comment]
Thanks, we were able to narrow down the issue.

**Comment by RonnyPfannschmidt** [comment]
@muh182 based on that issue, can this one be closed?

**Comment by muh182** [comment]
Yes, please. Thanks!

**Comment by RonnyPfannschmidt** [comment]
thanks
