### ISSUE TITLE
Drop Python 2.6 and 3.3 from CI

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/execnet#77]
https://github.com/pytest-dev/execnet/pull/76#issuecomment-396962235

**Comment by RonnyPfannschmidt** [comment]
closed in https://github.com/pytest-dev/execnet/commit/16c081914c8f5c9534e5cb26571dcc318a7ea426

**Comment by nicoddemus** [comment]
Oh OK did not see the commit on master. 👍
