### ISSUE TITLE
gateway spec: support envfile

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/execnet#80]
I think it would be good to have support for "envfile:PATH" next to "env:NAME=value" with the gateway spec (https://codespeak.net/execnet/basics.html#execnet.makegateway).

This format should be the same as with Docker's `--env-file`, i.e. a NAME=value pair per line.

**Comment by blueyed** [comment]
This is actually required to have env values containing "//" apparently:

> neither key nor value are allowed to contain "//"

https://github.com/pytest-dev/execnet/blob/d3384d311d0ec94b5ee06092bde54f011a306e33/execnet/xspec.py#L6-L13

**Comment by blueyed** [comment]
I had tried to work around this using `"//env:${(j-//env:-)${(@f)"$(<build/envfile.envdir.travis)"}}"` (zsh)

**Comment by RonnyPfannschmidt** [comment]
closing as super-seeded by #175 
instead of implementing the https://docs.docker.com/compose/env-file/ format, its safer to use a existing implementation
