### ISSUE TITLE
DumpError: can't serialize <class 'collections.OrderedDict'>

### ISSUE THREAD

**Issue by pombredanne** [pytest-dev/execnet#93]
This is using the latest execnet on Python 2.7 on Linux while evaluating execnet to provide some simple remoting support between Py2 and 3 and to pre-load some scancode processes for https://github.com/nexB/scancode-toolkit/issues/1397 and https://github.com/nexB/scancode-toolkit/issues/1400

**Comment by azrdev** [comment]
related to #52 ?

**Comment by RonnyPfannschmidt** [comment]
closing as not planned, the builtin serializer wont row more types, for now layer serialization on top

**Comment by pombredanne** [comment]
@RonnyPfannschmidt :+1: I should have closed this long ago as no longer relevant!
